version: '3'

services:
    database:
        image: arangodb
        environment:
            ARANGO_NO_AUTH: 1
        ports:
         - 8529:8529
        volumes:
         - data:/var/lib/arangodb3
         - data_app:/var/lib/aranagodb3-apps
        networks:
         - database

    nginx:
        image: nginx:1.19
        volumes:
         - ./config/nginx:/etc/nginx:ro
         - media:/media
        ports:
         - 80:8080
        depends_on:
         - web
        networks:
         - web


    web:
        build: backend
        depends_on:
         - database
        networks:
         - database
         - web

volumes:
    data:
    data_app:
    media:

networks:
    database:
    web:
