version: '3'

services:
    database:
        image: arangodb
        environment:
            ARANGO_NO_AUTH: 1
        ports:
         - 8529:8529
        volumes:
         - data:/var/lib/arangodb3
         - data_app:/var/lib/aranagodb3-apps
        networks:
         - database

    web:
        build:
            context: backend
            dockerfile: prod.Dockerfile
        env_file: .env
        depends_on:
         - database
        volumes:
         - media:/media
        networks:
         - database
         - web

    frontend:
        build:
            context: frontend
            dockerfile: prod.Dockerfile
        volumes:
         - media:/media
        ports:
         - 80:8080
        depends_on:
         - web
        networks:
         - web

volumes:
    data:
    data_app:
    media:

networks:
    database:
    web:
