version: '3'

services:
    database:
        image: arangodb
        environment:
            ARANGO_NO_AUTH: 1
        ports:
         - 8529:8529
        volumes:
         - data:/var/lib/arangodb3
         - data_app:/var/lib/aranagodb3-apps

    nginx:
        image: nginx:1.19
        volumes:
         - ./config/nginx:/etc/nginx

    web:
        build: backend

volumes:
    data:
    data_app:
